export default {
  name: "dadjoke",
  description: "Get a random dad joke",
  aliases: ["dad"],
  usage: "!dadjoke",
  cooldown: 5,
  async execute(message) {
    const dadJokes = [
      "I'm afraid for the calendar. Its days are numbered.",
      "My wife said I should do lunges to stay in shape. That would be a big step forward.",
      "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
      "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
      "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
      "What do you call a fish wearing a bowtie? Sofishticated.",
      "How do you follow Will Smith in the snow? You follow the fresh prints.",
      "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
      "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
      "What do you call a factory that makes okay products? A satisfactory.",
      "Dear Math, grow up and solve your own problems.",
      "What did the janitor say when he jumped out of the closet? Supplies!",
      "Have you heard about the chocolate record player? It sounds pretty sweet.",
      "What did the ocean say to the beach? Nothing, it just waved.",
      "Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.",
      "I only know 25 letters of the alphabet. I don't know y.",
      "How does the moon cut his hair? Eclipse it.",
      "What did one wall say to the other? I'll meet you at the corner.",
      "What did the zero say to the eight? That belt looks good on you.",
      "A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.'",
      "Where do fruits go on vacation? Pear-is!",
      "I asked my dog what's two minus two. He said nothing.",
      "What did Baby Corn say to Mama Corn? Where's Pop Corn?",
      "What's the best time to go to the dentist? Tooth hurt-y.",
      "Why did the math book look so sad? Because of all of its problems!",
      "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
      "What do you call cheese that isn't yours? Nacho cheese.",
      "Why did the scarecrow win an award? He was outstanding in his field.",
      "How does a penguin build its house? Igloos it together.",
      "Which state has the most streets? Rhode Island.",
      "What's a robot's favorite snack? Computer chips.",
      "I'm reading a book about anti-gravity. It's impossible to put down!",
      "Did you hear the rumor about butter? Well, I'm not going to spread it!",
      "Why couldn't the bicycle stand up by itself? It was two tired.",
      "What did the grape do when he got stepped on? He let out a little wine.",
    ]

    const joke = dadJokes[Math.floor(Math.random() * dadJokes.length)]
    await message.reply(`👨 ${joke}`)
  },
}
